name: CI Testing

on:
  push:
    branches: [main, TM-40-CI/CD]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
